### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by MeRichard123** [MeRichard123/Portfolio#1]
# Todo
- [x]  Implement React Router
- [x]  Add a filterable project section frontend and FullStack filter
- [x]  Add a list of all the blog using the dev.to API (Or maybe just some)
- [x]  Add a list of all my projects. Those hosted

NOTE: No new links should be added in the navigation bar. All to be added as buttons via React Router,
